# Project Configuration
# This file contains project-wide settings and paths

# Project Information
project:
  name: "cabinet_sensor_project"
  version: "1.0.0"
  description: "Sensor-enhanced vs baseline comparison for cabinet opening task"
  
# Paths Configuration
paths:
  # IsaacLab installation path
  isaaclab_root: "/home/larry/NVIDIA_DEV/isaac_grasp_ws/IsaacLab"
  
  # Project paths
  project_root: "/home/larry/NVIDIA_DEV/isaac_grasp_ws/cabinet_sensor_project"
  
  # Data paths
  data_root: "./data"
  results_dir: "./data/results"
  models_dir: "./data/models"
  configs_dir: "./data/configs"
  
  # Log paths
  log_root: "./logs"
  training_logs: "./logs/training"
  experiment_logs: "./logs/experiments"
  debug_logs: "./logs/debug"
  
  # Scripts paths
  scripts_dir: "./scripts"
  demo_scripts: "./scripts/demo"
  
# IsaacLab Integration
isaaclab:
  # Script execution settings
  use_isaaclab_wrapper: true          # Use ./isaaclab.sh wrapper
  python_executable: "python3"        # Python executable
  
  # Environment settings
  headless: true                       # Run headless by default
  enable_livestream: false             # Disable livestream
  
  # Isaac Sim settings
  isaac_sim:
    cleanup_processes: true            # Clean up processes after runs
    gpu_memory_check: true             # Check GPU memory before runs
    timeout_seconds: 3600              # Default timeout
    
# Experiment Management
experiments:
  # Default experiment settings
  default_seeds: [42, 43, 44]          # Default random seeds
  default_num_envs: 64                  # Default number of environments
  default_max_iterations: 1000          # Default max iterations
  
  # Comparison experiment settings
  comparison:
    num_seeds: 3                       # Number of seeds for comparison
    max_iterations: 2000               # Max iterations for comparison
    cleanup_wait: 60                   # Wait time between runs (seconds)
    
  # Results management
  results:
    auto_save: true                    # Auto-save results
    save_format: "json"                # Save format: json, csv, both
    compress_logs: false               # Compress log files
    
# Visualization Settings
visualization:
  # Default plot settings
  default_style: "seaborn"             # Default plot style
  default_dpi: 300                     # Default DPI
  figure_size: [12, 8]                 # Default figure size
  
  # Color scheme
  colors:
    sensor_color: "#2E86AB"            # Sensor version color
    baseline_color: "#A23B72"          # Baseline version color
    success_color: "#28A745"           # Success color
    failure_color: "#DC3545"           # Failure color
    
# System Settings
system:
  # Process management
  process_management:
    enable_cleanup: true               # Enable automatic cleanup
    cleanup_interval: 60               # Cleanup interval (seconds)
    gpu_memory_threshold: 80           # GPU memory threshold (%)
    
  # Performance settings
  performance:
    num_cpu_threads: 8                 # Number of CPU threads
    memory_limit_ratio: 0.8            # Memory limit ratio
    
# Development Settings
development:
  # Debug settings
  debug_mode: false                    # Enable debug mode
  verbose_logging: false               # Enable verbose logging
  
  # Testing settings
  testing:
    run_tests: true                    # Run tests during development
    test_coverage: true                # Generate test coverage reports
    
# Configuration Validation
validation:
  # Validate paths on startup
  validate_paths: true
  
  # Validate dependencies
  validate_dependencies: true
  
  # Validate GPU availability
  validate_gpu: true
