# Sensor-Enhanced Version Configuration
# This file contains settings specific to the sensor-enhanced version

# Import base configuration
base_config: "base_config.yaml"

# Environment Configuration (extends base)
env:
  # Sensor-specific settings
  sensors:
    enable_contact_sensors: true      # Enable contact sensors
    contact_sensor_resolution: 64     # Sensor resolution
    contact_sensor_frequency: 240     # Sensor update frequency (Hz)
    
    # Sensor placement
    finger_sensors: true              # Enable finger sensors
    palm_sensors: true                # Enable palm sensors
    wrist_sensors: false              # Disable wrist sensors
    
    # Sensor processing
    sensor_noise_std: 0.01           # Sensor noise standard deviation
    sensor_filter_cutoff: 10.0       # Low-pass filter cutoff frequency
    
  # Observation dimensions (with sensors)
  observation_space:
    total_dim: 43                     # Total observation dimension
    
    # Breakdown of observation
    robot_state_dim: 18               # Robot joint states
    task_state_dim: 13                # Task-specific states
    sensor_dim: 12                    # Contact sensor data
    
# Training Configuration (sensor-specific)
training:
  # Sensor-specific training parameters
  sensor_training:
    use_sensor_curriculum: true       # Use curriculum learning for sensors
    sensor_weight_schedule: "linear"  # Sensor weight scheduling
    initial_sensor_weight: 0.1        # Initial sensor weight
    final_sensor_weight: 1.0          # Final sensor weight
    
  # Network architecture for sensors
  network:
    sensor_encoder:
      hidden_sizes: [128, 64]         # Sensor encoder hidden layers
      activation: "relu"              # Activation function
      use_batch_norm: true            # Use batch normalization
      
    fusion_layer:
      fusion_type: "concatenation"    # Fusion method: concatenation, attention
      fusion_dim: 256                 # Fusion layer dimension
      
# Reward Configuration (sensor-specific)
reward:
  # Sensor-based rewards
  sensor_rewards:
    contact_reward: 0.5               # Reward for proper contact
    force_magnitude_reward: 0.3       # Reward for appropriate force
    stability_reward: 0.2             # Reward for stable grasp
    
  # Sensor-based penalties
  sensor_penalties:
    excessive_force_penalty: -0.5     # Penalty for excessive force
    instability_penalty: -0.3         # Penalty for unstable contact
    
# Experiment Configuration
experiment:
  name: "cabinet_sensor_enhanced"
  description: "Sensor-enhanced version with contact sensing"
  
  # Sensor-specific logging
  sensor_logging:
    log_sensor_data: true             # Log sensor data
    sensor_log_interval: 50           # Sensor logging interval
    save_sensor_plots: true           # Save sensor visualization plots
    
# Visualization Configuration
visualization:
  # Sensor visualization
  sensor_viz:
    show_contact_forces: true         # Show contact force visualization
    show_sensor_heatmap: true         # Show sensor heatmap
    contact_force_scale: 0.01         # Contact force visualization scale
    
# File paths
paths:
  script_name: "cabinet_rl_with_sensors_new.py"
  log_prefix: "sensor_enhanced"
  model_save_name: "sensor_model"
