# Isaac Lab Asset Configuration - 216传感器完整版本
# Generated: $(date)

inspire_hand_with_sensors:
  class_type: RigidObject
  
  # USD file path
  usd_path: "../usd/inspire_hand_processed_with_pads.usd"
  
  # Physics configuration
  spawn:
    rigid_props:
      rigid_body_enabled: true
      kinematic_enabled: false
      disable_gravity: false
      
  # Contact sensor configuration
  contact_sensors:
    # 手掌传感器 (112个)
    palm_sensor_pads:
      prim_path: "/World/inspire_hand_with_sensors/palm_sensor_pad_*"
      update_period: 0.005  # 200 FPS
      force_threshold: 0.098  # 10g
      torque_threshold: 0.1
      
    # 拇指1传感器 (96个)  
    thumb_sensor_1_pads:
      prim_path: "/World/inspire_hand_with_sensors/thumb_sensor_1_pad_*"
      update_period: 0.005  # 200 FPS
      force_threshold: 0.147  # 15g
      torque_threshold: 0.1
      
    # 拇指2传感器 (8个)
    thumb_sensor_2_pads:
      prim_path: "/World/inspire_hand_with_sensors/thumb_sensor_2_pad_*"
      update_period: 0.005  # 200 FPS
      force_threshold: 0.147  # 15g
      torque_threshold: 0.1

# 传感器统计
sensor_summary:
  total_sensors: 216
  palm_sensors: 112
  thumb1_sensors: 96
  thumb2_sensors: 8
  sampling_rate: "200FPS"
