# Isaac Lab配置文件 - Inspire Hand with Sensor Pads
# 包含316个接触点: 112个palm + 96个thumb1 + 8个thumb2 + 96个thumb3 + 4个force传感器

metadata:
  version: "1.0"
  description: "Inspire Hand with comprehensive sensor pads - all sensor locations"
  contact_points: 316
  
sensor_configuration:
  palm_sensors:
    count: 112
    layout: "14x8"
    pad_size: "3.0x3.0x0.6mm"
    color: "green"
    
  thumb_sensor_1:
    count: 96
    layout: "8x12"
    pad_size: "1.2x1.2x0.6mm"
    color: "blue"
    
  thumb_sensor_2:
    count: 8
    layout: "2x4"
    pad_size: "1.2x1.2x0.6mm"
    color: "orange"
    
  thumb_sensor_3:
    count: 96
    layout: "8x12"
    pad_size: "1.2x1.2x0.6mm"
    color: "purple"
    trigger_force: "15g"
    range: "20N"
    framerate: "200FPS"
    
  force_sensors:
    count: 4
    locations: ["thumb_force_sensor_1", "thumb_force_sensor_2", "thumb_force_sensor_3", "thumb_force_sensor_4"]

# Isaac Lab机械臂配置
robot:
  class_type: "Articulation"
  usd_path: "./usd/inspire_hand_processed_with_pads.usd"
  
actuators:
  position_actuator:
    class_type: "DCMotor"
    saturation_effort: 100.0

# 默认关节位置
default_joint_pos:
  ".*": 0.0
