# Isaac Lab Configuration for Inspire Hand with 988 Sensor Pads
# Generated on: 2025-07-27 12:03:44
# Total sensor pads: 988 (including little_sensor_3: 9 pads)

inspire_hand_cfg:
  usd_path: "{ISAAC_LAB_ASSETS}/Robots/inspire_hand_processed_with_pads.usd"
  
  # Sensor configuration - 988 total pads
  sensors:
    total_sensor_pads: 988  # All sensors combined - Little3 added
